version: "3.8"

services:
  data-service:
    build: ./data-service
    ports:
      - "3000:3000"
    volumes:
      - ./data-service:/app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo-chmury:27017/esport
    restart: always
    networks:
      - esportlol
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 2

  mongo:
    image: mongo:6
    container_name: mongo-chmury
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - esportlol


  analytics-service:
    build: ./analytics-service
    ports:
      - "4000:4000"
    volumes:
      - ./analytics-service:/app
    restart: always
    depends_on:
      - mongo
    networks:
      - esportlol
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 2




  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - analytics-service
      - data-service
    restart: always
    networks:
    - esportlol

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - PORT=8080
      - REACT_APP_API=http://backend:3000/api
    ports:
      - "8080:8080"
    depends_on:
      - analytics-service
      - data-service
    networks:
      - esportlol



volumes:
  mongo_data:

networks:
  esportlol: