version: "3.8"

services:
  backend:
    build:
      context: ./backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/esport
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - mongo
    restart: always


  mongo:
    image: mongo:6
    container_name: mongo-chmury
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - PORT=8080
      - REACT_APP_API=http://backend:3000/api
    ports:
      - "8080:8080"
    depends_on:
      - backend



volumes:
  mongo_data: